### ISSUE TITLE
[개발] 포스터 인터랙션(애니메이션) 활성화 시점 변경 (hover -> click)

### ISSUE THREAD

**Issue by hjjae2** [pigs-pango-team/gg-pigs-web#110]
**[개발] 포스터 인터랙션(애니메이션) 활성화 시점 변경 (hover -> click)**

1. 포스터 애니메이션 활성화되는 시점 변경하겠습니다.
- 현재는 hover -> 변경 후 click

**Comment by kkwongs** [comment]
hover에서 click으로 바꾸는 이유가 무엇인가요?

**Comment by hjjae2** [comment]
@kkwongs 

> hover에서 click으로 바꾸는 이유가 무엇인가요?

아! 원래 계획이 click 으로 하는 것이었으나, 임시로 hover 로 해놓았던 부분이었습니다!

**Comment by kkwongs** [comment]
확인했습니다!
