### ISSUE TITLE
[개발] 빌드 target 모드 변경 의견

### ISSUE THREAD

**Issue by hjjae2** [pigs-pango-team/gg-pigs-web#119]
**[개발] 빌드 target 모드 변경 의견**

프로젝트 빌드 시 아래와 같은 문구를 확인했습니다.

```
When using nuxt generate, you should set target: 'static' in your nuxt.config
       👉 Learn more about it on https://go.nuxtjs.dev/static-target
```

(링크의 내용을 확인해보니)
`Full static mode` 라는 것이 있는데요. (요약하면) SSR 을 위해 사용하는 AsyncData(), Fetch() 함수가 계속해서 호출되지 않도록 설정하는 부분이라고 하네요. 걸어둔 링크의 동영상을 보시면 쉽게 이해하실 수 있을 것 같습니다.

예를 들면,
현재는 신청 페이지(/apply) 에서 로고를 클릭하여 메인 페이지로 이동하면 (네트워크 상에)API 호출하는 부분이 찍히는데요.
full static mode 로 설정하니 API 호출을 하지 않는 것을 확인했습니다.
> 이 부분은 직접 한번 확인해보셔도 좋을 것 같아요.

SSR 적용 된 페이지에 반복적인 API 호출이 필요 없다면, 해당 설정 적용해도 좋을 것 같은데요. 
의견 부탁드립니다!

> https://ko.nuxtjs.org/blog/going-full-static/

**Comment by kkwongs** [comment]
지금 광고 신청하기 페이지를 작성하는데 계속해서 호출하지 않은 `user.js` api가 실행되는 이유일 수도 있을 것 같아서 적용해보면 좋을 것 같습니다. ![image](https://user-images.githubusercontent.com/43363739/106159414-1b0b2200-61c8-11eb-9939-8571a417d383.png)
