### ISSUE TITLE
[리팩토링] 메인 페이지 퍼블리싱

### ISSUE THREAD

**Issue by kkwongs** [pigs-pango-team/gg-pigs-web#124]
**[리팩토링] 메인 페이지 퍼블리싱**

1. 메인 페이지의 레이아웃, 이미지(로고, 아이콘) 크기와 위치, 글자 크기를 수정하겠습니다.

**Comment by hjjae2** [comment]
"메인 페이지의 레이아웃" 은 

헤더의 사이즈 수정을 의미하는 것인가요??
