### ISSUE TITLE
[개발] 신청 페이지 floating action button 추가

### ISSUE THREAD

**Issue by kkwongs** [pigs-pango-team/gg-pigs-web#128]
**[개발] 신청 페이지 floating action button 추가**

1. 광고 신청 페이지 (step2)에 floating action button을 추가하겠습니다.

**Comment by hjjae2** [comment]
`floating action button` 이라 함은, 아래의 것을 말하는 것이죠??

![image](https://user-images.githubusercontent.com/35790290/106745763-ecc49100-6664-11eb-99b3-82e0ca081c81.png)

**Comment by kkwongs** [comment]
넵!
