### ISSUE TITLE
[리팩토링] 메인 페이지 포스터 자세히 보기 버튼 수정

### ISSUE THREAD

**Issue by kkwongs** [pigs-pango-team/gg-pigs-web#130]
**[리팩토링] 메인 페이지 포스터 자세히 보기 버튼 수정**

1. 포스터의 자세히 보기 버튼이 보이지 않는 상태에서 버튼 위치를 클릭 시 실행되는 것을 수정하겠습니다.

**Comment by hjjae2** [comment]
:+1:
