### ISSUE TITLE
[개발] 메인페이지 포스터 모바일 버전 개선 (임시)

### ISSUE THREAD

**Issue by hjjae2** [pigs-pango-team/gg-pigs-web#132]
**[개발] 메인페이지 포스터 모바일 버전 개선 (임시)**

1. 모바일 화면에서, (메인페이지의) 포스터 안의 내용이 overflow 되는 것의 문제를 수정하겠습니다. (디자인이 나오기 전 임시로 수정해두겠습니다!)

**Comment by kkwongs** [comment]
알겠습니다!

**Comment by hjjae2** [comment]
@kkwongs 

#133 

해당 이슈의 작업은 선 반영되었습니다! 

확인 부탁드려요!!

**Comment by kkwongs** [comment]
확인했습니다!
