### ISSUE TITLE
[개발] 로그인 api 수정 (json -> x-www-form-urlencoded)

### ISSUE THREAD

**Issue by hjjae2** [pigs-pango-team/gg-pigs-web#142]
## [개발] 로그인 api 수정 (json -> x-www-form-urlencoded)

1. (뒷단의 Login API 가 변경됨에 따라) 로그인 API의 헤더, 데이터 전송 방식에 대해 수정합니다.
- 기존: json
- 개선: x-www-form-urlencoded

```
// json
{
  key1: value1,
  key2: value2
}
```

```
// x-www-form-urlencoded
key1=value1&key2=value2
```

**Comment by hjjae2** [comment]
> Reference 
> 1. https://gist.github.com/jays1204/703297eb0da1facdc454
> 2. https://taehoonkoo.tistory.com/232
> 3. https://velog.io/@y_dragonrise/Web-Get-Post-%EC%9A%94%EC%B2%AD-%EB%B0%A9%EC%8B%9D

> _" application/json이 {key:value}의 형태로 전송되며 application/x-www-form-urlencoded가 key-value&key=value...의 형태로 전송되는것 ... "_

> _" application/x-www-form-urlencoded type message는 하나의 큰 query string 형태로 서버에 전송된다. 
> name/value 짝은 &로 구분되고 이름과 value는 =로 구분된다. 
> application/x-www-form-urlencoded 은 사이즈가 큰 binary data나 non-ASCII 를 포함한 text data를 보내기 부적합하며, 이런 경우에는 "multipart/form-data"를 사용해야 한다. "_

> " '&' 문자로 매개변수를 구분하고, '=' 문자로 매개변수의 이름과 값을 분리함. 바이너리 데이터안에 위와 같은 문자가 포함될 경우 잘못 해석됌 "

**Comment by kkwongs** [comment]
그러면 Post 요청 시 json형식이 아닌 querystring으로 코드를 작성해야 되는 건가요?

**Comment by hjjae2** [comment]
@kkwongs 
> 그러면 Post 요청 시 json형식이 아닌 querystring으로 코드를 작성해야 되는 건가요?

그렇습니다. 다만, GET 요청 시의 QueryString 과 POST 요청 시의 QueryString 방식은 차이가 있습니다. 

Ex. URL 에 노출(Header 에 포함) vs URL 에 비노출(Body 에 포함)

> Reference1. https://kimcoder.tistory.com/149
> Reference2. https://m.blog.naver.com/PostView.nhn?blogId=jdub7138&logNo=221039834501&proxyReferer=https:%2F%2Fwww.google.com%2F

흠.. 근데 POST 시에 QueryString 의 형태로 요청하는 것이 적절한지에 대해서는 의견이 좀 나뉘는 것 같기도한데요.. 조금 더 찾아봐보겠습니다!

**Comment by hjjae2** [comment]
아래 글도 많이 도움되는 것 같습니다. 

https://yuda.dev/250
https://stackoverflow.com/a/5876875

**Comment by hjjae2** [comment]
QueryString in GET vs POST 주제에 대해 찾아보다가 POST + QueryString 의 사용이 적절한지에 대한 글도 보게되었는데요.

결론적으로는 POST + QueryString 의 형태로 사용해도 괜찮을 것 같습니다.

> (제대로 이해한게 맞다면) 일부 글에서 "POST 의 경우 QueryString 의 형태를 사용하지 말고, Body 에 데이터를 담아서 요청해라!" 라는 말이 있었는데, POST 에서는 QueryString 의 형태로 요청하면 Body에 담기기 때문에 적절하지 않은..? 글인 것 같네요!

**Comment by kkwongs** [comment]
@hjjae2 

> Reference
> 1. https://blog.naver.com/writer0713/221853596497
> 2. https://lemontia.tistory.com/922

저도 좀 찾아봤는데 요즘엔 QueryString의 형태보다는 JSON타입을 많이 사용하는 것 같습니다. FormData를 이용해서 form을 일일히 쓰는 것보다는 json으로 관리하는 것이 훨씬 편하다고 생각합니다.

> default Content-Type은 'application/json'이 아니라 'application/x-www-form-urlencoded'다.

만약 데이터를 json형태로 주고 받는다면 클라이언트 쪽에서 Content-Type에 'application/json'을 추가해주면 될 것입니다.

혹시 QueryString의 형태를 사용해야되는 이유가 있다면 어떤 것일까요?

**Comment by hjjae2** [comment]
@kkwongs 

좋은 의견 감사합니다. 말씀해주신 것 처럼 정말로 QueryString  을 사용해야 하는 이유가 특별히 없어서 해당 이슈는 Close 하겠습니다! (즉, 현재의 Json 형태 유지)

---

관련해서 조금 더 내용 훑어 보았는데요. 발견한 내용 공유해보겠습니다!

저희가 지금 사용하고 있는 @nuxt/axios 에서는 아래와 같은 Default 설정이 있는 것으로 확인했습니다.

```
// PATH : {project_path}/node_modules/axios/lib/defaults.js
...

var defaults = {
  adapter: getDefaultAdapter(),

  transformRequest: [function transformRequest(data, headers) {

  ...

  if (utils.isURLSearchParams(data)) {
    setContentTypeIfUnset(headers, 'application/x-www-form-urlencoded;charset=utf-8');
    return data.toString();
  }
  if (utils.isObject(data)) {
    setContentTypeIfUnset(headers, 'application/json;charset=utf-8');
    return JSON.stringify(data);
  }
...
```

즉, axios 와 함께 전송되는 데이터(payload, data)의 유형에 따라 `Content-Type` 을 수정해주네요.

아래와 같이 요청하면, `applicaiton/x-www-form-urlencoded` content-type 이 설정되는 것을 확인했습니다.
```
payload = {
  id : ~,
  pw : ~
}

axios.post(`${baseApiUrl}/api/v1/login`, qs.stringify(payload), {
  // headers: { 'content-type': 'application/x-www-form-urlencoded' },
  timeout: 10000,
  withCredentials: true,
});
```

반면에 아래와 같이 요청하면, `application/json` content-type 이 설정되는 것을 확인했습니다.

```
payload = {
  id : ~,
  pw : ~
}

axios.post(`${baseApiUrl}/api/v1/login`, payload, {
  // headers: { 'content-type': 'application/x-www-form-urlencoded' },
  timeout: 10000,
  withCredentials: true,
});
```

( 단, 주석 처리되어 있는 `headers` 설정을 주게되면 해당 값이 우선순위로 적용되는 것을 확인했습니다. )

( 참고: Global Config 설정을 통해 Default 설정 가능합니다. https://www.npmjs.com/package/axios, 'Config Defaults'  )
